const STORAGE='market_table_offline_v1';
const DRAFT='market_table_draft_v1';
const COMMODITIES=[
['Rice','Imported Commercial Rice - Special','Blue tag','kg'],['Rice','Imported Commercial Rice - Premium','Yellow tag','kg'],['Rice','Imported Commercial Rice - Well Milled','White tag','kg'],['Rice','Imported Commercial Rice - Regular Milled','White tag','kg'],['Rice','Local Commercial Rice - Special','Blue tag','kg'],['Rice','Local Commercial Rice - Premium','Yellow tag','kg'],['Rice','Local Commercial Rice - Well Milled','White tag','kg'],['Rice','Local Commercial Rice - Regular Milled','White tag','kg'],
['Fish','Bangus','med, 3-4 pcs/kg','kg'],['Fish','Tilapia','med, 5-6 pcs/kg','kg'],['Fish','Galunggong Local','med, 12-14 pcs/kg','kg'],['Fish','Galunggong Imported','med, 12-14 pcs/kg','kg'],['Fish','Alumahan','med, 4-6 pcs/kg','kg'],
['Livestock & Poultry','Beef Rump','lean meat / tapadera','kg'],['Livestock & Poultry','Beef Brisket','meat w/ bones','kg'],['Livestock & Poultry','Pork Kasim','','kg'],['Livestock & Poultry','Pork Liempo','','kg'],['Livestock & Poultry','Whole Chicken','fully dressed','pc'],['Livestock & Poultry','Chicken Egg','medium size','pc'],
['Lowland Vegetables','Ampalaya','4-5 pcs/kg','kg'],['Lowland Vegetables','Sitao','3-4 small bundles','kg'],['Lowland Vegetables','Pechay Native','3-4 small bundles','kg'],['Lowland Vegetables','Cucumber','','kg'],['Lowland Vegetables','Okra','','kg'],['Lowland Vegetables','Squash','Suprema variety','kg'],['Lowland Vegetables','Eggplant','3-4 small bundles','kg'],['Lowland Vegetables','Patola','','kg'],['Lowland Vegetables','Tomato','15-18 pcs/kg','kg'],
['Highland Vegetables','Cabbage Scorpio','750g-1kg/head','kg'],['Highland Vegetables','Carrots','8-10 pcs','kg'],['Highland Vegetables','Habitchuelas','Baguio beans','kg'],['Highland Vegetables','White Potato','10-12 pcs','kg'],['Highland Vegetables','Atsal Bell Pepper','','kg'],['Highland Vegetables','Chayote','','kg'],
['Spices','Red Onion Local','13-15 pcs/kg','kg'],['Spices','Red Onion Imported','','kg'],['Spices','White Onion Local','','kg'],['Spices','White Onion Imported','','kg'],['Spices','Garlic Imported','','kg'],['Spices','Garlic Native','','kg'],['Spices','Ginger','','kg'],['Spices','Chilli Labuyo','','kg'],['Spices','Sili Bisaya','','kg'],
['Fruits','Calamansi','','kg'],['Fruits','Banana Saba','','kg'],['Fruits','Banana Lakatan','8-10 pcs/kg','kg'],['Fruits','Banana Latundan','10-12 pcs/kg','kg'],['Fruits','Papaya','2-3 pcs/kg','kg'],['Fruits','Mango Carabao','3-4 pcs/kg','kg'],['Fruits','Avocado','','kg'],
['Other Commodities','Sugar Refined','','kg'],['Other Commodities','Sugar Washed','','kg'],['Other Commodities','Sugar Brown','','kg'],['Other Commodities','Cooking Oil Palm 350ml','','btl'],['Other Commodities','Cooking Oil Palm 1L','','btl'],['Other Commodities','White Corn Grits #10','','kg'],['Other Commodities','White Corn Grits #12','','kg'],['Other Commodities','Sweet Potato','','kg'],['Other Commodities','Cassava','','kg'],['Other Commodities','Taro Gabi','','kg']
].map((x,i)=>({id:'C'+String(i+1).padStart(3,'0'),cat:x[0],name:x[1],spec:x[2],unit:x[3]}));
function $(id){return document.getElementById(id)}
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function money(v){return v?Number(v).toFixed(2):''}
function today(){return new Date().toISOString().slice(0,10)}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch(e){return[]}}
function save(a){localStorage.setItem(STORAGE,JSON.stringify(a));refreshRecords()}
function renderTable(){let body='',last='';COMMODITIES.forEach(c=>{if(c.cat!==last){body+=`<tr class="cat-row"><td colspan="10">${c.cat}</td></tr>`;last=c.cat}body+=`<tr data-id="${c.id}"><td class="sticky-col"><div class="commodity"><b>${c.name}</b>${c.spec?`<small>${c.spec}</small>`:''}</div></td><td class="unit">${c.unit}</td>${[1,2,3,4,5].map(n=>`<td><input class="cell-in" type="number" inputmode="decimal" step="0.01" data-store="s${n}" oninput="calcRow(this.closest('tr'))"></td>`).join('')}<td class="auto low" data-auto="low"></td><td class="auto" data-auto="high"></td><td class="auto" data-auto="prev"></td></tr>`});$('entryBody').innerHTML=body}
function calcRow(tr){let vals=[...tr.querySelectorAll('input')].map(i=>parseFloat(i.value)).filter(v=>!isNaN(v)&&v>0);let low='',high='',prev='';if(vals.length){low=Math.min(...vals);high=Math.max(...vals);prev=vals.reduce((a,b)=>a+b,0)/vals.length}tr.querySelector('[data-auto=low]').textContent=money(low);tr.querySelector('[data-auto=high]').textContent=money(high);tr.querySelector('[data-auto=prev]').textContent=money(prev)}
function gather(){let rows=[];document.querySelectorAll('#entryBody tr[data-id]').forEach(tr=>{let c=COMMODITIES.find(x=>x.id===tr.dataset.id);let inputs=[...tr.querySelectorAll('input')];let vals=inputs.map(i=>parseFloat(i.value)).filter(v=>!isNaN(v)&&v>0);if(vals.length)rows.push({commodityId:c.id,category:c.cat,commodity:c.name,unit:c.unit,store1:inputs[0].value||'',store2:inputs[1].value||'',store3:inputs[2].value||'',store4:inputs[3].value||'',store5:inputs[4].value||'',low:Math.min(...vals),high:Math.max(...vals),prevailing:vals.reduce((a,b)=>a+b,0)/vals.length})});return rows}
function fileData(file){return new Promise((res,rej)=>{if(!file)return res(null);let r=new FileReader();r.onload=()=>res({name:file.name,type:file.type,size:file.size,data:r.result});r.onerror=rej;r.readAsDataURL(file)})}
async function buildRecord(){let rows=gather();if(!rows.length){toast('Enter at least one price');return null}let att=null;try{att=await fileData($('attachment').files[0])}catch(e){toast('Attachment could not be saved');return null}return{id:'FORM-'+Date.now().toString(36).toUpperCase(),date:$('entryDate').value,market:$('market').value,enumerator:$('enumerator').value.trim(),rows,attachment:att,createdAt:new Date().toISOString()}}
async function saveForm(){let rec=await buildRecord();if(!rec)return;let arr=load();arr.unshift(rec);try{save(arr);localStorage.removeItem(DRAFT);clearTable(false);toast('Saved offline')}catch(e){toast('Storage full. Export backup or reduce file size.')}}
function saveDraft(){let rows=gather();let draft={date:$('entryDate').value,market:$('market').value,enumerator:$('enumerator').value,rows};localStorage.setItem(DRAFT,JSON.stringify(draft));toast('Draft saved')}
function restoreDraft(){let d;try{d=JSON.parse(localStorage.getItem(DRAFT)||'null')}catch(e){}if(!d)return;$('entryDate').value=d.date||today();$('market').value=d.market||'Cogon Market';$('enumerator').value=d.enumerator||'';(d.rows||[]).forEach(r=>{let tr=document.querySelector(`#entryBody tr[data-id="${r.commodityId}"]`);if(tr){['store1','store2','store3','store4','store5'].forEach((k,i)=>tr.querySelectorAll('input')[i].value=r[k]||'');calcRow(tr)}})}
function clearTable(confirmIt=true){if(confirmIt&&!confirm('Clear all entered prices?'))return;document.querySelectorAll('#entryBody input').forEach(i=>i.value='');document.querySelectorAll('[data-auto]').forEach(td=>td.textContent='');$('attachment').value='';}
function showTab(name,btn){['entry','records','tools'].forEach(v=>$(v+'View').classList.toggle('hidden',v!==name));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');if(name==='records')refreshRecords()}
function refreshRecords(){let arr=load();$('recordCount').textContent=arr.length+' saved forms';$('recordsList').innerHTML=arr.length?arr.map(r=>`<div class="record"><b>${r.date} — ${r.market}</b><small>${r.rows.length} commodities • ${r.enumerator||'No enumerator'} ${r.attachment?'• file attached':''}</small><div class="btnbar" style="margin-top:9px"><button class="btn primary" onclick="exportOneCSV('${r.id}')">CSV</button><button class="btn danger" onclick="deleteOne('${r.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No saved forms yet.</div>'}
function deleteOne(id){if(!confirm('Delete this saved form?'))return;save(load().filter(r=>r.id!==id));toast('Deleted')}
function deleteAll(){if(!confirm('Delete all saved forms? Export backup first if needed.'))return;localStorage.removeItem(STORAGE);refreshRecords();toast('All deleted')}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function download(name,text,type){let b=new Blob([text],{type});let u=URL.createObjectURL(b);let a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function rowsToCSV(records){let h=['FormID','Date','Market','Enumerator','Commodity ID','Commodity','Category','Unit','Store 1','Store 2','Store 3','Store 4','Store 5','Low','High','Prevailing','Attachment','Created At'];let rows=[];records.forEach(r=>(r.rows||[]).forEach(x=>rows.push([r.id,r.date,r.market,r.enumerator,x.commodityId,x.commodity,x.category,x.unit,x.store1,x.store2,x.store3,x.store4,x.store5,x.low,x.high,x.prevailing,r.attachment?.name||'',r.createdAt])));return [h,...rows].map(r=>r.map(csvCell).join(',')).join('\n')}
function exportCSV(){download('market-entry-'+today()+'.csv',rowsToCSV(load()),'text/csv');toast('CSV exported')}
function exportOneCSV(id){let r=load().filter(x=>x.id===id);download('market-entry-'+(r[0]?.date||today())+'.csv',rowsToCSV(r),'text/csv')}
function exportJSON(){download('market-entry-backup-'+today()+'.json',JSON.stringify(load(),null,2),'application/json');toast('Backup exported')}
function importJSON(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let incoming=JSON.parse(r.result);if(!Array.isArray(incoming))throw new Error();let existing=load();let ids=new Set(existing.map(x=>x.id));save([...incoming.filter(x=>x.id&&!ids.has(x.id)),...existing]);toast('Backup imported')}catch(err){toast('Invalid backup file')}};r.readAsText(f);e.target.value=''}
window.onload=()=>{renderTable();$('entryDate').value=today();restoreDraft();refreshRecords()};